AWSTemplateFormatVersion: '2010-09-09'
Description: Network Load Balancer

Parameters:
  NLBName:
    Description: Network Load Balancer Name
    Type: String
    Default: nlb-moh-test
    
  NLBScheme:
    Description: Network Load Balancer Scheme
    Type: String
    Default: internal
    AllowedValues:
      - internet-facing
      - internal
  
  NLBAcessLogBucket:
    Description: Network Load Balancer access log bucket
    Type: String
    Default: s3-prod-logs-syd-959603514248
      
  CertificateArn:
    Description: Certificate ARN
    Type: String
    Default: arn:aws:acm:ap-southeast-2:959603514248:certificate/8fa5a4db-d142-49d6-b543-6e5cb9ea015c

  VpcId:
    Description: Enter the VPCId that the system will be deployed to
    Type: AWS::EC2::VPC::Id
    Default: vpc-6880690c

  WebSubnetA:
    Description: Web Subnet A ID
    Type: AWS::EC2::Subnet::Id
    Default: subnet-30d70a46

  WebSubnetB:
    Description: Web Subnet B ID
    Type: AWS::EC2::Subnet::Id
    Default: subnet-9e289cfa
      
  WebSubnetC:
    Description: Web Subnet C ID
    Type: AWS::EC2::Subnet::Id
    Default: subnet-4489411d
      
  EC2Instance1:
    Description: EC2Instance1
    Type: String
    Default: i-0718e63316a116334

  EC2Instance2:
    Description: EC2Instance2
    Type: String
    Default: i-0997e946d2a3a2957
    
  Application:
    Description: Application Name or web site
    Type: String
    Default: nlb-test-moh.dpi.nsw.gov.au
    
  BusinessOwner:
    Description: AWS Account Alias
    Type: String
    Default: aws-disrd-dev
   
  BusinessUnit:
    Description: Name of team branch
    Type: String
    Default: vdc
    
  CFNTemplate:
    Description: Cloudformation template file name
    Type: String
    Default: create-internal-nlb.yaml
    
  Criticality:
    Description: critical,vhigh,high,med,low
    Type: String
    Default: low
    AllowedValues:
      - low
      - med
      - high
      - vhigh
      - critical
      
  Environment:
    Description: prd/tst/dev
    Type: String
    Default: tst
    AllowedValues:
      - dev
      - tst
      - prd
      
  RecID:
    Description: Cherwell CSP number
    Type: String
    Default: CSPxxxx
    
  SystemOwner:
    Description: Email address of the system owner
    Type: String
    Default: mohammad.ayub@dpie.nsw.gov.au

  Role:
    Description: Role description
    Type: String
    Default: 'web'
 
Resources:
  NLBListener443:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NLBTargetGroup
      LoadBalancerArn: !Ref   NetworkLoadBalancer
      Port: 443
      Protocol: TCP

  NLBListener80:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NLBTargetGroup
      LoadBalancerArn: !Ref   NetworkLoadBalancer
      Port: 80
      Protocol: TCP
      
  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: true
        - Key: access_logs.s3.bucket
          Value: !Ref NLBAcessLogBucket
        - Key: access_logs.s3.prefix
          Value: 
            !Join
              - ''
              - - !Ref NLBName
                - '-alb-access-logs'
        - Key: deletion_protection.enabled
          Value: false
        - Key: load_balancing.cross_zone.enabled
          Value: true     
      Name: !Ref NLBName
      Scheme: !Ref NLBScheme
      Subnets:
        - !Ref WebSubnetA
        - !Ref WebSubnetB
        - !Ref WebSubnetC
      Type: network
      IpAddressType: ipv4
      Tags:
        - Key: Name
          Value: !Ref NLBName
        - Key: Application
          Value: !Ref Application
        - Key: BusinessOwner
          Value: !Ref BusinessOwner
        - Key: BusinessUnit
          Value: !Ref BusinessUnit
        - Key: CFNTemplate
          Value: !Ref CFNTemplate
        - Key: Criticality
          Value: !Ref Criticality
        - Key: Environment
          Value: !Ref Environment
        - Key: RecID
          Value: !Ref RecID
        - Key: SystemOwner
          Value: !Ref SystemOwner
        - Key: Role
          Value: !Ref Role

  NLBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: True
      HealthCheckIntervalSeconds: 30
      HealthCheckPort: '80'
      HealthCheckProtocol: 'TCP'
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      Name: !Ref NLBName 
      Port: 80
      Protocol: 'TCP'
      TargetGroupAttributes:
        - Key: 'deregistration_delay.timeout_seconds'
          Value: 300      
      Targets:
        - Id:
            Ref: EC2Instance1
          Port: 80
        - Id:
            Ref: EC2Instance2
          Port: 80
      TargetType: 'instance'
      UnhealthyThresholdCount: 3
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Ref NLBName
        - Key: Application
          Value: !Ref Application
        - Key: BusinessOwner
          Value: !Ref BusinessOwner
        - Key: BusinessUnit
          Value: !Ref BusinessUnit
        - Key: CFNTemplate
          Value: !Ref CFNTemplate
        - Key: Criticality
          Value: !Ref Criticality
        - Key: Environment
          Value: !Ref Environment
        - Key: RecID
          Value: !Ref RecID
        - Key: SystemOwner
          Value: !Ref SystemOwner
        - Key: Role
          Value: !Ref Role         

Outputs:
  LoadBalancerDetails:
    Description: Load Balancer DNSName
    Value: !GetAtt NetworkLoadBalancer.DNSName
