AWSTemplateFormatVersion: 2010-09-09
Description: 'Mohammad standard ec2 with SG an eni deployment'

Resources:
 MySG:
  Type: "AWS::EC2::SecurityGroup"
  Properties:
    GroupName: "mohammad-vpc01-ssh"
    GroupDescription: "Security group with ssh and rdp access"
    VpcId: vpc-0da9da6feea5676db
    SecurityGroupIngress:
    - CidrIp: "10.0.0.0/8"
      IpProtocol: "tcp"
      FromPort: "22"
      ToPort: "22"
      Description: "DISRD SSH Network Logon Access"
    - CidrIp: "10.0.0.0/8"
      IpProtocol: "tcp"
      FromPort: "3389"
      ToPort: "3389"
      Description: "DISRD RDP Network Logon Access"
    Tags:
    - Key: Name
      Value: sg-moh-poc-ssh-rdp
